//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IscsiDiskSpec) DeepCopyInto(out *IscsiDiskSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IscsiDiskSpec.
func (in *IscsiDiskSpec) DeepCopy() *IscsiDiskSpec {
	if in == nil {
		return nil
	}
	out := new(IscsiDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IscsiHostSpec) DeepCopyInto(out *IscsiHostSpec) {
	*out = *in
	if in.Luns != nil {
		in, out := &in.Luns, &out.Luns
		*out = make([]IscsiLunSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IscsiHostSpec.
func (in *IscsiHostSpec) DeepCopy() *IscsiHostSpec {
	if in == nil {
		return nil
	}
	out := new(IscsiHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IscsiLunSpec) DeepCopyInto(out *IscsiLunSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IscsiLunSpec.
func (in *IscsiLunSpec) DeepCopy() *IscsiLunSpec {
	if in == nil {
		return nil
	}
	out := new(IscsiLunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IscsiStorageSpec) DeepCopyInto(out *IscsiStorageSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]IscsiDiskSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IscsiStorageSpec.
func (in *IscsiStorageSpec) DeepCopy() *IscsiStorageSpec {
	if in == nil {
		return nil
	}
	out := new(IscsiStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Iscsigateway) DeepCopyInto(out *Iscsigateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Iscsigateway.
func (in *Iscsigateway) DeepCopy() *Iscsigateway {
	if in == nil {
		return nil
	}
	out := new(Iscsigateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Iscsigateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IscsigatewayList) DeepCopyInto(out *IscsigatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Iscsigateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IscsigatewayList.
func (in *IscsigatewayList) DeepCopy() *IscsigatewayList {
	if in == nil {
		return nil
	}
	out := new(IscsigatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IscsigatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IscsigatewaySpec) DeepCopyInto(out *IscsigatewaySpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = make([]IscsiStorageSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]IscsiHostSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IscsigatewaySpec.
func (in *IscsigatewaySpec) DeepCopy() *IscsigatewaySpec {
	if in == nil {
		return nil
	}
	out := new(IscsigatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IscsigatewayStatus) DeepCopyInto(out *IscsigatewayStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IscsigatewayStatus.
func (in *IscsigatewayStatus) DeepCopy() *IscsigatewayStatus {
	if in == nil {
		return nil
	}
	out := new(IscsigatewayStatus)
	in.DeepCopyInto(out)
	return out
}
